import React from "react";

const reportTypes = [
  {
    title: "Monthly Revenue Report",
    description: "Detailed breakdown of monthly income",
    icon: "bi bi-graph-up-arrow",
    lastGenerated: "2026-01-05",
  },
  {
    title: "Expense Summary",
    description: "Comprehensive expense tracking",
    icon: "bi bi-receipt",
    lastGenerated: "2026-01-04",
  },
  {
    title: "Profit & Loss Statement",
    description: "P&L statement for the fiscal year",
    icon: "bi bi-cash-coin",
    lastGenerated: "2026-01-03",
  },
  {
    title: "Balance Sheet",
    description: "Current financial position",
    icon: "bi bi-bank2",
    lastGenerated: "2026-01-02",
  },
  {
    title: "Accounts Receivable Report",
    description: "Outstanding payments analysis",
    icon: "bi bi-credit-card-2-front",
    lastGenerated: "2026-01-01",
  },
  {
    title: "Tax Summary",
    description: "Tax liability and deductions",
    icon: "bi bi-file-earmark-text",
    lastGenerated: "2025-12-31",
  },
];

const FInanceReport = () => {
  return (
    <div className="financial-reports-page">
      <div className="reports-header">
        <div>
          <h2 className="reports-title">Financial Reports</h2>
          <p className="reports-subtitle">Generate and download financial reports</p>
        </div>
        <div className="header-actions">
          <button className="btn btn-outline-secondary me-2">
            <i className="bi bi-calendar"></i> Custom Range
          </button>
          <button className="btn btn-primary">
            <i className="bi bi-plus-lg"></i> New Report
          </button>
        </div>
      </div>

      <div className="reports-stats">
        <div className="stat-card">
          <div className="stat-icon revenue-icon">
            <i className="bi bi-cash-stack"></i>
          </div>
          <div className="stat-content">
            <h5>Total Revenue (This Month)</h5>
            <h3>₹12,45,000</h3>
            <p className="trend-up">+12.5% from last month</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon expense-icon">
            <i className="bi bi-wallet2"></i>
          </div>
          <div className="stat-content">
            <h5>Total Expenses</h5>
            <h3>₹8,20,000</h3>
            <p className="trend-down">-5.2% from last month</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon profit-icon">
            <i className="bi bi-graph-up"></i>
          </div>
          <div className="stat-content">
            <h5>Net Profit</h5>
            <h3>₹4,25,000</h3>
            <p className="trend-up">+28.3% from last month</p>
          </div>
        </div>
      </div>

      <div className="reports-grid">
        {reportTypes.map((report, index) => (
          <div key={index} className="report-card">
            <div className="report-icon-wrapper">
              <i className={report.icon}></i>
            </div>
            <h4 className="report-title">{report.title}</h4>
            <p className="report-description">{report.description}</p>
            <p className="report-date">Last generated: {report.lastGenerated}</p>
            <div className="report-actions">
              <button className="btn btn-outline-primary btn-sm me-2">
                <i className="bi bi-eye"></i> View
              </button>
              <button className="btn btn-outline-success btn-sm me-2">
                <i className="bi bi-download"></i> Download
              </button>
              <button className="btn btn-primary btn-sm">
                <i className="bi bi-arrow-clockwise"></i> Generate
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="recent-reports-card mt-4">
        <h4 className="mb-3">Recently Generated Reports</h4>
        <div className="table-responsive">
          <table className="table table-hover">
            <thead className="table-light">
              <tr>
                <th>Report Name</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Format</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Monthly Revenue Report - Dec 2025</td>
                <td>David Chen</td>
                <td>2026-01-05</td>
                <td><span className="badge bg-info text-dark">PDF</span></td>
                <td>
                  <button className="btn btn-outline-secondary btn-sm me-2"><i className="bi bi-eye"></i></button>
                  <button className="btn btn-outline-success btn-sm"><i className="bi bi-download"></i></button>
                </td>
              </tr>
              <tr>
                <td>Expense Summary - Q4 2025</td>
                <td>Finance Team</td>
                <td>2026-01-04</td>
                <td><span className="badge bg-warning text-dark">Excel</span></td>
                <td>
                  <button className="btn btn-outline-secondary btn-sm me-2"><i className="bi bi-eye"></i></button>
                  <button className="btn btn-outline-success btn-sm"><i className="bi bi-download"></i></button>
                </td>
              </tr>
              <tr>
                <td>Profit & Loss Statement - 2025</td>
                <td>David Chen</td>
                <td>2026-01-03</td>
                <td><span className="badge bg-primary">PDF</span></td>
                <td>
                  <button className="btn btn-outline-secondary btn-sm me-2"><i className="bi bi-eye"></i></button>
                  <button className="btn btn-outline-success btn-sm"><i className="bi bi-download"></i></button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default FInanceReport;
